### ISSUE TITLE
odd text rendering

### ISSUE THREAD

**Issue by fdncred** [rgwood/escape-artist#4]
I was trying to debug some weirdness in nushell and I'm typing `n` `u` and I'm getting some things that I'm not typing.

* ~/src/escape-artist <-- from prompt
* you can see an `n` between some of the escapes <-- got it, this is what i typed
* then this pops up - no clue where it's coming from
```
ode -e `console.log(require('node:process').argv)` `a b c`
```
* Then further down I get this `../nu_scripts/make_release/get_coverage.nu` <-- again, no idea where it's coming from.
* Later on there's a `ver`

![image](https://github.com/rgwood/escape-artist/assets/343840/39e40e7c-4b77-4c62-b710-345a0f6d9646)

**Comment by fdncred** [comment]
Ugh, I just figured it out. It's hints. LOL. How distracting. It's a little tricky following what's going on with the escapes.

**Comment by rgwood** [comment]
Glad I’m not the only one using this tool! :)
