### ISSUE TITLE
Draw text based on ansi escapes

### ISSUE THREAD

**Issue by fdncred** [rgwood/escape-artist#5]
feature request

I was thinking that it would be cool when you have ansi escape colors that you draw the text in that color.

Like these
* CSI 48;2;12;12;12;38;2;211;215;207m
* CSI 38;5;5m
* CSI 38;2;96;96;96m

When there's fg and bg, draw both. When there's just fg, make the text that color. When there's just bg, make that bg that color with a contrasting text color.

Another related idea is to color the text the color specified.

Like this
```
CSI 48;2;211;215;207;38;2;12;12;12m 08:20:31 PM
```
so `08:20:31 PM` would be the fg/bg color specified before it.

I ask about this because I think it would help tracking where things are at because I find myself doing split windows with escape-artist on one side and the web browser on the other. Type a character, then see what it does. Sometimes it's hard to see.

**Comment by rgwood** [comment]
Agreed, that would be very useful. Same issue as https://github.com/rgwood/escape-artist/issues/1 right?

**Comment by fdncred** [comment]
LOL. I guess I really want this feature. Sorry for the dupe. 

I looked at the code and didn't really see where to add it. Web != good. Although, I think I'm using some ts/js thing that translates ansi colors to web colors in the vscode extension. I could be remembering wrong though.

**Comment by rgwood** [comment]
Here's the function that creates a human-readable description of an escape code that sets a colour:
https://github.com/rgwood/escape-artist/blob/master/src/main.rs#L746

At a high level, I think the way to implement this would be:

1. Use global variables in the Rust code to keep track of the current foreground+background colour
2. Update that function to return information about colour in a more structured way (like a struct with RGB values), use it to set the global variables
3. Add `Option<Color>` fields to `VteEventDto::Print` and/or `VteEventDto::GenericEscape`, set the fields using the global variables
4. In the front-end (`script.js`), use those fields to set the foreground+background colours appropriately

I think I could do this in a couple hours but am not 100% sure when I will get to it. It does sound fun, I might try to do it one of these weekends.
